// <auto-generated />
using Deals;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Deal.Migrations
{
    [DbContext(typeof(DealContext))]
    [Migration("20240322171144_priceAsfloat")]
    partial class priceAsfloat
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.17");

            modelBuilder.Entity("Deals.Deal", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("BigImage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("Price")
                        .HasColumnType("REAL");

                    b.Property<string>("ShopId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ShopLink")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SmallImage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UnitType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("UnitsFrom")
                        .HasColumnType("REAL");

                    b.Property<float>("UnitsTo")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("ShopId");

                    b.ToTable("Deals");
                });

            modelBuilder.Entity("Deals.Shop", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Stores");
                });

            modelBuilder.Entity("Deals.Deal", b =>
                {
                    b.HasOne("Deals.Shop", "Shop")
                        .WithMany("Deals")
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("Deals.Shop", b =>
                {
                    b.Navigation("Deals");
                });
#pragma warning restore 612, 618
        }
    }
}
